#!/usr/bin/env python
import sys
import rospy
from ur5_kinematics.testing import PathTest

if __name__ == '__main__':    
    rospy.init_node("kinematics_test", sys.argv)
    path = [
        [-0.3, -0.15, 0.35],
        [-0.3,  0.00, 0.40],
        [-0.3, 0.15, 0.35],
        [-0.45, 0.15, 0.30],
        [-0.6, 0.15, 0.35],
        [-0.6, 0.00, 0.40],
        [-0.6, -0.15, 0.35],
    ]
    test = PathTest('/pos_joint_traj_controller/follow_joint_trajectory', '/goal_pose', path)
    
    while True:
        test.update()