#!/usr/bin/env python

from math import sin
import rospy

from ur5_kinematics.testing import PathTest
import sys


if __name__ == '__main__':    
    rospy.init_node("kinematics_test", sys.argv)
    points = [
        [-0.2, -0.15, 0.35],
        [-0.2, 0.15, 0.35],
        [-0.5, 0.15, 0.35],
        [-0.5, -0.15, 0.35]
    ]
    test = PathTest('/pos_joint_traj_controller/follow_joint_trajectory', '/kinematics_server/goal_pose', points)
    
    while True:
        test.update()